insert into countries (name) values ('Russia');
insert into countries (name) values ('USA');
insert into countries (name) values ('Germany');

insert into areas (name, countrie_id) values ('Moscow_area', 1);
insert into areas (name, countrie_id) values ('Novosibirsk_area', 1);
insert into areas (name, countrie_id) values ('Sochi_area', 1);
insert into areas (name, countrie_id) values ('Texas', 2);
insert into areas (name, countrie_id) values ('California', 2);
insert into areas (name, countrie_id) values ('Utah', 2);
insert into areas (name, countrie_id) values ('Berlin_area', 3);
insert into areas (name, countrie_id) values ('Hamburg_area', 3);
insert into areas (name, countrie_id) values ('Bavaria_area', 3);

insert into cities (name, area_id) values ('Moscow', 1);
insert into cities (name, area_id) values ('Dmitrov', 1);
insert into cities (name, area_id) values ('Podolsk', 1);
insert into cities (name, area_id) values ('Novosibirsk', 2);
insert into cities (name, area_id) values ('Karasuk', 2);
insert into cities (name, area_id) values ('Berdsk', 2);
insert into cities (name, area_id) values ('Sochi', 3);
insert into cities (name, area_id) values ('Golovinka', 3);
insert into cities (name, area_id) values ('Vishnevka', 3);
insert into cities (name, area_id) values ('Ostin', 4);
insert into cities (name, area_id) values ('Dallas', 4);
insert into cities (name, area_id) values ('Huston', 4);
insert into cities (name, area_id) values ('Los-Angeles', 5);
insert into cities (name, area_id) values ('San-Fracisco', 5);
insert into cities (name, area_id) values ('Sacramento', 5);
insert into cities (name, area_id) values ('Salt-Lake-City', 6);
insert into cities (name, area_id) values ('Beaver', 6);
insert into cities (name, area_id) values ('Richfield', 6);
insert into cities (name, area_id) values ('Berlin', 7);
insert into cities (name, area_id) values ('Schönefeld', 7);
insert into cities (name, area_id) values ('Vishnevka', 7);
insert into cities (name, area_id) values ('Hamburg', 8);
insert into cities (name, area_id) values ('Iserbrook', 8);
insert into cities (name, area_id) values ('Barsbüttel', 8);
insert into cities (name, area_id) values ('München', 9);
insert into cities (name, area_id) values ('Augsburg', 9);
insert into cities (name, area_id) values ('Erding', 9);